[package]
name = "mdbook-git"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.40"
git2 = "0.20.2"
mdbook = "0.4.51"
regex = "1.11.1"
semver = "1.0.26"
serde_json = "1.0.140"
