[package]
name = "mdbook-git"
version = "0.2.2"
edition = "2024"
description = "Insert git commit files and diffs into mdbook"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
clap = "4.5.40"
git2 = "0.20.2"
mdbook = "0.4.51"
regex = "1.11.1"
semver = "1.0.26"
serde_json = "1.0.140"
